export interface Team {
  id: number;
  nombre: string;
  categoria: string;
  division: string;
  logo: string;
}

export const TEAMS: Team[] = [
  {
    id: 1,
    nombre: "Real Zaragoza",
    categoria: "Masculino",
    division: "2ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/142.png",
  },
  {
    id: 2,
    nombre: "Real Madrid",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/418.png",
  },
  {
    id: 3,
    nombre: "FC Barcelona",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/131.png",
  },
  {
    id: 4,
    nombre: "Atlético de Madrid",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/13.png",
  },
  {
    id: 5,
    nombre: "Real Sociedad",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/681.png",
  },
  {
    id: 6,
    nombre: "Real Betis",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/150.png",
  },
  {
    id: 7,
    nombre: "Sevilla FC",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/368.png",
  },
  {
    id: 8,
    nombre: "Athletic Club",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/621.png",
  },
  {
    id: 9,
    nombre: "Valencia CF",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/1049.png",
  },
  {
    id: 10,
    nombre: "Villarreal CF",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/1050.png",
  },
  {
    id: 11,
    nombre: "Girona FC",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/12321.png",
  },
  {
    id: 12,
    nombre: "RC Celta",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/940.png",
  },
  {
    id: 13,
    nombre: "CA Osasuna",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/331.png",
  },
  {
    id: 14,
    nombre: "RCD Mallorca",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/237.png",
  },
  {
    id: 15,
    nombre: "Rayo Vallecano",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/367.png",
  },
  {
    id: 16,
    nombre: "Getafe CF",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/3709.png",
  },
  {
    id: 17,
    nombre: "Deportivo Alavés",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/1108.png",
  },
  {
    id: 18,
    nombre: "UD Las Palmas",
    categoria: "Masculino",
    division: "1ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/472.png",
  },
  {
    id: 19,
    nombre: "Granada CF",
    categoria: "Masculino",
    division: "2ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/16795.png",
  },
  {
    id: 20,
    nombre: "Málaga CF",
    categoria: "Masculino",
    division: "2ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/1084.png",
  },
  {
    id: 21,
    nombre: "Cádiz CF",
    categoria: "Masculino",
    division: "2ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/2687.png",
  },
  {
    id: 22,
    nombre: "UD Almería",
    categoria: "Masculino",
    division: "2ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/3302.png",
  },
  {
    id: 23,
    nombre: "Real Sporting",
    categoria: "Masculino",
    division: "2ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/2448.png",
  },
  {
    id: 24,
    nombre: "Racing Santander",
    categoria: "Masculino",
    division: "2ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/630.png",
  },
  {
    id: 25,
    nombre: "RC Deportivo",
    categoria: "Masculino",
    division: "2ª Division",
    logo: "https://tmssl.akamaized.net/images/wappen/head/897.png",
  },
];
